name: Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ steps.create_token.outputs.token }}
          release-type: simple

